AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run static web site with Apache web server
Resources:
  OmerCFInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: omer_key
      SecurityGroups:
        - Httpand ssh
      Tags:
        - Key: Name
          Value: Web server of Kittens Carousel
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 /var/www/html
          cd /var/www/html
          wget https://raw.githubusercontent.com/omerbayrak11/clarusway_aws_devops_workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/omerbayrak11/clarusway_aws_devops_workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.jpg
          wget https://raw.githubusercontent.com/omerbayrak11/clarusway_aws_devops_workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.jpg
          wget https://raw.githubusercontent.com/omerbayrak11/clarusway_aws_devops_workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.jpg